export default function Head() {
  return (
  <head>
      <title>Cookie Stand Admin</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
  </head>
  )
}